[versions]
agp = "8.3.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.7.0"
material = "1.12.0"
constraintlayout = "2.1.4"
lifecycleLivedataKtx = "2.7.0"
lifecycleViewmodelKtx = "2.7.0"
navigationFragment = "2.7.7"
navigationUi = "2.7.7"
retrofit = "2.11.0"
converterGson = "2.11.0"
picasso = "2.5.2"
legacySupportV4 = "1.0.0"
gson = "2.6.2"
cardview = "1.0.0"
logging-interceptor = "4.12.0"
okhttp = "4.9.0"
gs = "4.4.2"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
retrofit = {group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit"}
converter-gson = {group = "com.squareup.retrofit2", name="converter-gson", version.ref = "converterGson"}
picasso = {group = "com.squareup.picasso", name = "picasso", version.ref = "picasso"}
legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacySupportV4" }
gson = {group = "com.google.code.gson", name = "gson", version.ref = "gson"}
cardview = {group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
logging-interceptor = {group =  "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "logging-interceptor"}
okhttp = {group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp"}

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
google-services = {id = "com.google.gms.google-services", version.ref = "gs"}


